# Generated by Django 5.2.4 on 2026-02-23 16:15

import django.db.models.deletion
import media_manager.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='media_manager.folder')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=media_manager.models.upload_to)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('other', 'Other')], default='other', max_length=20)),
                ('size', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='media_manager.folder')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='media', to='media_manager.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['owner', 'parent'], name='media_manag_owner_i_acba91_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['created_at'], name='media_manag_created_5ac689_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('name', 'parent', 'owner')},
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['owner'], name='media_manag_owner_i_a24566_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='media_manag_uploade_84ee2e_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['folder'], name='media_manag_folder__4209de_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['file_type'], name='media_manag_file_ty_98fb6e_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['created_at'], name='media_manag_created_a74302_idx'),
        ),
    ]
